apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: demo-backend-it-ingress
spec:
  rules:
    - host: demobackend-it-test.dev.insee.io
      http:
        paths:
          - path: /
            backend:
              serviceName: demo-backend-it-svc
              servicePort: 8080