name: ci

on:
  push:
    branches: master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: tester login
        env:
          CR_PAT: ${{ secrets.PAT }}
        run: |
          echo $CR_PAT | docker login ghcr.io -u USERNAME --password-stdin
          echo "...... hello!"
          kubectl version --client
      - name: tester CLI
        env:
          CR_PAT: ${{ secrets.PAT }}
        run: |
          kubectl version --client
          kubectl apply -f https://k8s.io/examples/controllers/nginx-deployment.yaml
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Maven
        run: mvn -B package
      - name: Upload jar
        uses: actions/upload-artifact@v2
        with:
          name: jar
          path: target/demo-backend-0.0.1-SNAPSHOT.jar
      - name: Login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAT }}
      - name: Build and push to ghcr
        id: docker_build
        uses: docker/build-push-action@v1
        with:
          context: .
          file: ./Dockerfile
          push: true
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}
          registry: ghcr.io
          #repository: achile73/demos/demo-backend
          tag_with_ref: true
      - name: deploy to cluster
        uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: set image --record deployment/my-app container=${{ github.repository }}:${{ github.sha }}


