name: ci

on:
  push:
    branches: master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: tester login
        env:
          CR_PAT: ${{ secrets.PAT }}
        run: echo $CR_PAT | docker login ghcr.io -u USERNAME --password-stdin
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Maven
        run: mvn -B package
      - name: Upload jar
        uses: actions/upload-artifact@v2
        with:
          name: jar
          path: target/demo-backend-0.0.1-SNAPSHOT.jar
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      #- name: Login to ghrc
      #  env:
      #    CR_PAT: ${{ secrets.PAT }}
      #  uses: docker/login-action@v1
      #  run: echo $CR_PAT | docker login ghcr.io -u USERNAME --password-stdin
      - uses: docker/login-action@v1
    	  with:
      	registry: ghcr.io
      	username: ${{ github.repository_owner }}
      	password: ${{ secrets.PAT }}
      - name: Build and push to ghcr
        id: docker_build
        uses: docker/build-push-action@v1
        with:
          context: .
          file: ./Dockerfile
          push: true
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}
          registry: docker.pkg.github.com
          repository: achile73/demos/demo-backend
          #tag_with_ref: true
          tags: ghcr.io/achile73/demos/demo-backend:latest
